POST http://localhost:3000/api/jobs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGVseW5ncmltb2xkYnkiLCJpZCI6MSwiaWF0IjoxNjcxNzQxMjc1fQ.2ZrbTKOz-xa30ZaK9QLBXJ7ww2a3jNlFKQ41VT_Jimc

{
  "jobDescription":
    "{'type':'doc','content':[{'type':'paragraph','content':[{'type':'text','text':'teee'}]}]}",
  "positionTitle": "test",
  "location": "remote",
  "company": "test inc",
  "applied": "2022-12-22",
  "compensation": "5k",
  "interviews": ["2022-12-22", "2021-01-02"],
  "status": "offered"
}