GET http://localhost:8080/api/jobs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGVseW5ncmltb2xkYnkiLCJuYW1lIjoiS2F0ZWx5biIsImlkIjo5MDYsImlhdCI6MTY3MzY3MjMxNiwiZXhwIjoxNjczNjcyMzE2fQ.JQFSz2ePrmGnoqrKl0Ls3t8MSihuO9cMIp1YWsERBq0
Userid: 906