version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=trackerDev
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    command:
      ['redis-server', '--appendonly', 'yes', '--requirepass', 'password']
    volumes:
      - ./redis_data:/data
volumes:
  db:
  redis:
