DELETE http://localhost:8080/api/auth/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGVseW5ncmltb2xkYnkiLCJuYW1lIjoiS2F0ZWx5biIsImlkIjo5MDYsImlhdCI6MTY3MzY3MTI3NCwiZXhwIjoxNjczNjcxMjc0fQ.O2GGgyOEhmE5w1HAhTWyHeOQhSpzJP8DRMJm-Wcu21Y
Userid: 906 