DELETE http://localhost:8080/api/auth/logout 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGVseW5ncmltb2xkYnkiLCJuYW1lIjoiS2F0ZWx5biIsImlkIjo4OSwiaWF0IjoxNzIwNzQxMTc3LCJleHAiOjE3MjA3NDIzNzd9.8_avfMRUkg2bX9QCM2051--HDxVYMZ7uCJZj3FeNjic 
Userid: 89